### ISSUE TITLE
Choosing a Java GUI Framework 

### ISSUE THREAD

**Issue by Tymisko** [FreakyF/Weather-track#10]
To implement our GUI, we need to choose a Java GUI framework that will suit our project needs. The choice of framework can significantly impact the development process and the capabilities of our application. Therefore, this task requires careful consideration and research.

The tasks to be addressed in this issue include:

- **Research**: Look into various Java GUI frameworks. This may include but is not limited to, Swing, JavaFX, and SWT. Understand the pros and cons of each framework, their community support, and their compatibility with our current project.
- **Performance Consideration**: Consider the performance implications of each framework. Some may be more lightweight than others, some may offer better customization, and others may be better suited for complex interfaces.
- **Documentation and Learning Curve**: Evaluate the quality of documentation and the learning curve associated with each framework. A well-documented framework with a lot of learning resources can speed up development.
- **Decision**: Based on the above factors, decide on a framework to use for our project.

**Acceptance Criteria**:

1. A thorough comparison of different Java GUI frameworks has been conducted, considering factors such as ease of use, community support, performance, and compatibility with our project.
2. A framework has been chosen and the choice is justified with reference to our specific project needs and the research conducted.
3. The team is informed about the chosen framework and agrees with the decision.

**Comment by FreakyF** [comment]
| Feature                         | Swing         | JavaFX       | SWT          | AWT         |
|---------------------------------|---------------|--------------|--------------|-------------|
| Cross-platform compatibility   | ✔             | ✔            | ✔            | ✔           |
| Modern UI design                | ✘             | ✔            | ✔            | ✘           |
| Rich UI components              | ✔             | ✔            | ✔            | ✘           |
| Layout managers                 | ✔             | ✔            | ✔            | ✘           |
| Animation and transitions       | ✘             | ✔            | ✔            | ✘           |
| 3D graphics support             | ✘             | ✔            | ✘            | ✘           |
| Mobile and touch support        | ✘             | ✔            | ✘            | ✘           |
| Web integration                 | ✘             | ✔            | ✘            | ✘           |
| Data binding                    | ✘             | ✔            | ✘            | ✘           |
| CSS styling                     | ✘             | ✔            | ✘            | ✘           |
| Internationalization support    | ✔             | ✔            | ✔            | ✘           |
| Community and support           | ✔             | ✔            | ✔            | ✔           |
| Learning curve                  | Moderate      | Moderate     | Moderate     | Easy        |
| Active development              | No (Maintenance Mode)  | Yes  | Yes  | No (Maintenance Mode) |

# Summary

The GUI Framework for this project will be JavaFX, because it allows for a more modern UI design, is more commonly and also it's in active development.
